/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fibonacci;

/**
 *
 * @author daden2468
 */
public class FibonacciGUI extends javax.swing.JFrame {

    /**
     * Creates new form FibonacciGUI
     */
    public FibonacciGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actionButton = new javax.swing.JButton();
        input = new javax.swing.JTextField();
        output = new javax.swing.JTextField();
        title = new javax.swing.JLabel();
        setup1 = new javax.swing.JLabel();
        example = new javax.swing.JLabel();
        ask = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        actionButton.setText("Find the Fibonacci number");
        actionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionButtonActionPerformed(evt);
            }
        });
        getContentPane().add(actionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));
        getContentPane().add(input, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 40, 30));

        output.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputActionPerformed(evt);
            }
        });
        getContentPane().add(output, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 380, 40));

        title.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        title.setForeground(new java.awt.Color(255, 0, 0));
        title.setText("Fibonacci Numbers");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 150, 30));

        setup1.setText("The first 9 Fibonacci numbers are as follows:");
        getContentPane().add(setup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        example.setText("1, 1, 2, 3, 5, 8, 13, 21, 34, ...");
        getContentPane().add(example, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, 10));

        ask.setText("Enter the Fibonacci term you would like to see: ");
        getContentPane().add(ask, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * This causes the Fibonacci sequence to be calculated to the desired term
     * pre: the button must be pressed
     * post: the desired Fibonacci term is returned
     * @param evt 
     */
    private void actionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionButtonActionPerformed
        output.setText("Fibonacci #" + Integer.parseInt(input.getText()) + " is " + getFibonacci(Integer.parseInt(input.getText())));
    }//GEN-LAST:event_actionButtonActionPerformed

    private void outputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputActionPerformed
        
    }//GEN-LAST:event_outputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FibonacciGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FibonacciGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FibonacciGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FibonacciGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FibonacciGUI().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actionButton;
    private javax.swing.JLabel ask;
    private javax.swing.JLabel example;
    private javax.swing.JTextField input;
    private javax.swing.JTextField output;
    private javax.swing.JLabel setup1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    
    /**\
     * This method calculates the Fibonacci term at the argument
     * pre: none
     * post: returns the desired term
     */
    private int getFibonacci(int num) {
        int b = num;
        if (b == 1 || b == 2) {
            return 1;
        } else {
            return (getFibonacci(b - 1) + getFibonacci(b - 2));
        }
    }
}
