/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author daden2468
 */
public class FractionSimplifier extends javax.swing.JFrame {

    /**
     * Creates new form FractionSimplifier
     */
    public FractionSimplifier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        setup1 = new javax.swing.JLabel();
        setup2 = new javax.swing.JLabel();
        setup3 = new javax.swing.JLabel();
        numInput = new javax.swing.JTextField();
        denInput = new javax.swing.JTextField();
        calc = new javax.swing.JButton();
        output = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Plantagenet Cherokee", 0, 18)); // NOI18N
        title.setForeground(new java.awt.Color(255, 153, 51));
        title.setText("Fraction Reducer");
        Panel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 140, 40));

        setup1.setText("This will reduce a fraction to lowest terms");
        Panel1.add(setup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        setup2.setText("Enter the numerator: ");
        Panel1.add(setup2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        setup3.setText("Enter the denominator:");
        Panel1.add(setup3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        numInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numInputActionPerformed(evt);
            }
        });
        Panel1.add(numInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 60, -1));
        Panel1.add(denInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 60, -1));

        calc.setText("Reduce to lowest terms");
        calc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcActionPerformed(evt);
            }
        });
        Panel1.add(calc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        output.setEditable(false);
        Panel1.add(output, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 290, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numInputActionPerformed

    }//GEN-LAST:event_numInputActionPerformed

    /**
     * this sets the output to the reduced fraction 
     * pre: button clicked 
     * post: output set
     * @param evt
     */
    private void calcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcActionPerformed
        output.setText(reduce(Integer.parseInt(numInput.getText()), Integer.parseInt(denInput.getText())));
    }//GEN-LAST:event_calcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FractionSimplifier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FractionSimplifier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FractionSimplifier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FractionSimplifier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FractionSimplifier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    private javax.swing.JButton calc;
    private javax.swing.JTextField denInput;
    private javax.swing.JTextField numInput;
    private javax.swing.JTextField output;
    private javax.swing.JLabel setup1;
    private javax.swing.JLabel setup2;
    private javax.swing.JLabel setup3;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    /**
     * This method returns the statement for the output, it also calls the
     * reducer method 
     * pre: none 
     * post: returns the output statement
     */
    private String reduce(int num, int den) {
        int divisor = reducer(num, den);
        return (num + "/" + den + " reduces to " + (num / divisor) + "/" + (den / divisor));
    }

    /**
     * This finds the GCD of the two integers inputs
     * pre: none
     * post: returns the GCD of the ints
     */
    private int reducer(int num, int den) {
        if (den == 0) {
            return num;
        } else {
            return (reducer(den, num % den));
        }
    }
}
