/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author daden2468
 */
public class NChooseR extends javax.swing.JFrame {

    /**
     * Creates new form NChooseR
     */
    public NChooseR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        calc = new javax.swing.JButton();
        output = new javax.swing.JTextField();
        nInput = new javax.swing.JTextField();
        rInput = new javax.swing.JTextField();
        setup1 = new javax.swing.JLabel();
        setup2 = new javax.swing.JLabel();
        setup3 = new javax.swing.JLabel();
        setup4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 255));
        title.setText("N Choose R");
        Panel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        calc.setText("Calculate the number of ways");
        calc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcActionPerformed(evt);
            }
        });
        Panel1.add(calc, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        output.setEditable(false);
        output.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputActionPerformed(evt);
            }
        });
        Panel1.add(output, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 240, 260, 30));

        nInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nInputActionPerformed(evt);
            }
        });
        Panel1.add(nInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 30, -1));
        Panel1.add(rInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 30, -1));

        setup1.setText("Enter number of objects there are to choose from:");
        Panel1.add(setup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 280, 20));

        setup2.setText("Enter the number of objects to choose: ");
        Panel1.add(setup2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 270, 20));

        setup3.setText("This program calculates the number of ways r different objects");
        Panel1.add(setup3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        setup4.setText(" can be chosen from a set of n objects");
        Panel1.add(setup4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        getContentPane().add(Panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void outputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputActionPerformed

    }//GEN-LAST:event_outputActionPerformed

    private void nInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nInputActionPerformed

    }//GEN-LAST:event_nInputActionPerformed

    
    /**
     * This causes the output field to be set to the number of ways
     * pre:button pressed
     * post:output set to number of ways
     * @param evt 
     */
    private void calcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcActionPerformed
        output.setText(nChooser((Integer.parseInt(nInput.getText())),(Integer.parseInt(rInput.getText()))));
    }//GEN-LAST:event_calcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NChooseR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NChooseR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NChooseR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NChooseR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NChooseR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    private javax.swing.JButton calc;
    private javax.swing.JTextField nInput;
    private javax.swing.JTextField output;
    private javax.swing.JTextField rInput;
    private javax.swing.JLabel setup1;
    private javax.swing.JLabel setup2;
    private javax.swing.JLabel setup3;
    private javax.swing.JLabel setup4;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    
    /**
     * This method return the number of ways to choose from the number of objects
     * pre: none
     * post: the number of ways is returned
     */
    private String nChooser(int n, int r) {
        int ways = fact(n)/(fact(r)*fact(n-r));
        
        return String.valueOf(ways);
    }
    
    /**
     * returns the factorial of the argument
     * pre: none
     * post: returns the factorial
     */
    public static int fact (int n) {
        if (n == 0 || n ==1) {
            return 1;
        } else {
            return (n * fact(n-1));
        }
    }

}
